---
title: "GPP Report"
date: '`r Sys.Date()`'
output: html_document
---

```{r set options, echo =FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

```{r initiate code, echo=F}
source("./code/resources/01_load-packages.R")

# exclude streams with GPP models still under constructions
streamsExclude = c('LECO','MCRA','COMO','WLOU')

streamsMod = streams[streams %ni% streamsExclude]

# load in mle models

mleFiles = list.files(path = "./ignore/metab-models/", pattern = ".*_full_mle.rds", full.names = TRUE) %>% unlist


mleModels = mleFiles %>% purrr::map(~readRDS(.x) %>% pluck('metab_daily') %>% dplyr::select(date, matches('GPP'))) %>% setNames(.,gsub("./ignore/metab-models/(.*_full_mle).rds","\\1",mleFiles)) %>% bind_rows(.id = "siteID")

gppFull = mleModels %>%
  dplyr::mutate(siteID = gsub("(\\w{4})_full_mle","\\1",siteID),
                jdate = lubridate::yday(date),
                year = lubridate::year(date)) %>%
  dplyr::select(siteID, date, year, jdate, GPP) %>% 
  dplyr::mutate(GPP = case_when(GPP <= 0 ~ 0,
                                      GPP >  ~NA_real_,
                                      TRUE ~ GPP)) %>% 
    filter(!is.na(GPP))
```


```{r gpp plot,fig.width=8,fig.height=6,fig.align='center', fig.cap="Daily "}
gppFull %>% ggplot+
  geom_point(aes(x = jdate, y = GPP, color = siteID)) +
  geom_smooth(aes(x = jdate, y =  GPP, color = siteID), method = 'loess', span = 0.25, color = "black", se = FALSE)+
  viridis::scale_color_viridis(discrete = TRUE)+
  # scale_y_log10()+
  facet_wrap(~siteID)+#, scales = 'free_y')+
  theme(legend.position = 'none')
```

